# Generated by Django 5.2.6 on 2026-08-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_detalleinventario_id_detalle_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleinventario',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleinventario',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
