# Generated by Django 5.2.6 on 2026-08-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_detalleinventario_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleinventario',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='detalleinventario',
            name='precio_venta',
        ),
    ]
