# Generated by Django 5.2.6 on 2026-08-26 18:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_remove_detalleinventario_costo_and_more'),
        ('producto', '0004_remove_producto_existencia'),
        ('sucursales', '0002_sucursal_codigo_postal_sucursal_codigo_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioSucursal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigente_desde', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo', models.BooleanField(default=True)),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sucursal', to='producto.producto')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sucursal', to='sucursales.sucursal')),
            ],
            options={
                'db_table': 'precio_sucursal',
                'indexes': [models.Index(fields=['id_producto', 'id_sucursal', 'activo', 'vigente_desde'], name='precio_sucu_id_prod_d91023_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('id_producto', 'id_sucursal'), name='uniq_precio_activo')],
            },
        ),
    ]
