[pytest]
DJANGO_SETTINGS_MODULE = RTR.settings_test
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths =
    tests
    inventario/tests
    ventas/tests
    sucursales/tests
    usuario/tests
    clientes/tests
    producto/tests
addopts =
    --cov=. --cov-report=term-missing --cov-config=.coveragerc
    --cov-fail-under=100
markers =
    slow: marks tests as slow
    integration: marks tests as integration tests
