# Generated by Django 5.2.6 on 2026-03-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigoSAT',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
