# Generated by Django 5.2.6

from django.db import migrations, models
import django.db.models.deletion


def mover_relacion_producto_movimiento(apps, schema_editor):
    """Migra la relación vieja Producto.id_movimientos -> Movimiento.id_producto."""
    Producto = apps.get_model('producto', 'Producto')
    Movimiento = apps.get_model('producto', 'Movimiento')
    for producto in Producto.objects.exclude(id_movimientos__isnull=True):
        movimiento = producto.id_movimientos
        if movimiento.id_producto_id is None:
            movimiento.id_producto_id = producto.id
            movimiento.save(update_fields=['id_producto'])


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimiento',
            name='id_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.producto'),
        ),
        migrations.RunPython(mover_relacion_producto_movimiento, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='producto',
            name='id_movimientos',
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='producto.producto'),
        ),
    ]
