# Generated by Django 5.2.6 on 2026-08-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_movimiento_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='surtir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
