# Generated by Django 5.2.6 on 2026-08-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='existencia',
        ),
    ]
