# Generated by Django 5.2.6 on 2026-08-26 18:06

import sucursales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursales', '0002_sucursal_codigo_postal_sucursal_codigo_sucursal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_postal',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo_sucursal',
            field=models.CharField(blank=True, default=sucursales.models._gen_codigo_sucursal, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='correo_electronico',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_sucursal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='numero_telefono',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
