# Generated by Django 5.2.6 on 2026-05-01 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0002_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('BAJO_STOCK', 'Bajo stock'), ('AGOTADO', 'Agotado')], max_length=20)),
                ('mensaje', models.CharField(max_length=255)),
                ('leido', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='producto.producto')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
